# Generated by Django 4.2.5 on 2024-03-19 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Onthego2', '0002_generatedprompt_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedprompt',
            name='budget',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='generatedprompt',
            name='days',
            field=models.TextField(default='1'),
        ),
        migrations.AddField(
            model_name='generatedprompt',
            name='place',
            field=models.TextField(default='Paris'),
        ),
        migrations.AddField(
            model_name='generatedprompt',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='generatedprompt',
            name='trip_type',
            field=models.TextField(default='Découverte'),
        ),
    ]
