# Generated by Django 4.2.5 on 2024-11-10 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Onthego2', '0006_itinerary_day_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='GeneratedPrompt',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
